# Generated by Django 5.2.5 on 2025-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano_publicacao',
            field=models.IntegerField(),
        ),
    ]
