# Generated by Django 5.2.5 on 2025-09-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='substituto',
            new_name='subtitulo',
        ),
    ]
