# Generated by Django 5.2.5 on 2025-08-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('substituto', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('idioma', models.CharField(default='portugues', max_length=255)),
                ('ano_publicacao', models.IntegerField(max_length=4)),
                ('paginas', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('dimensoes', models.CharField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editora')),
            ],
        ),
    ]
